version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: BiancaTicketSystem
      POSTGRES_USER: PrettyPrincessAdmin
      POSTGRES_PASSWORD: BiancaAdmin123!
    ports:
      - "8099:8099"

  backend:
    image: alfarana/wads-pp-fp-backend:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: BiancaTicketSystem
      DB_USER: PrettyPrincessAdmin
      DB_PASS: BiancaAdmin123!
      DB_HOST: db
      DB_PORT: 8099:8099
      DB_DIALECT: postgres
      DB_SSL: false
      PORT: 3034:3034
      ACCESS_TOKEN_SECRET: buttwebbythesecond
      BASE_URL: https://e2425-wads-l4ccg3-server.csbihub.id
      AUTH_EMAIL: almira.rana31@gmail.com
      AUTH_PASS: ycna futf ghbn izus
      FRONTEND_URL: https://e2425-wads-l4ccg3-client.csbihub.id
      CORS_ORIGIN: https://e2425-wads-l4ccg3-client.csbihub.id
      GEMINI_API_KEY: AIzaSyD9YrZsRyLT7WUCjiwcP_wPT1YMKE-hSAc
    ports:
      - "3034:3034"

  frontend:
    image: alfarana/wads-pp-fp-frontend:latest
    restart: always
    environment:
      DB_NAME: BiancaTicketSystem
      DB_USER: PrettyPrincessAdmin
      DB_PASS: BiancaAdmin123!
      DB_HOST: localhost
      DB_PORT: 8099:8099
      DB_DIALECT: postgres
      DB_SSL: false
      PORT: 3033:3033
      ACCESS_TOKEN_SECRET: buttwebbythesecond
      BASE_URL: https://e2425-wads-l4ccg3-client.csbihub.id
      AUTH_EMAIL: almira.rana31@gmail.com
      AUTH_PASS: ycna futf ghbn izus
      FRONTEND_URL: https://e2425-wads-l4ccg3-client.csbihub.id
      CORS_ORIGIN: https://e2425-wads-l4ccg3-client.csbihub.id
    depends_on:
      - backend
    ports:
      - "3033:3033"