version: "3.8"

services:
  backend:
    image: alfarana/wads-pp-fp-backend:latest
    restart: always
    environment:
      DB_NAME: BiancaTicketSystem
      DB_USER: PrettyPrincessAdmin
      DB_PASS: BiancaAdmin123!
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DIALECT: postgres
      DB_SSL: false
      PORT: 3034
      ACCESS_TOKEN_SECRET: buttwebbythesecond
      BASE_URL: http://localhost:3034
      AUTH_EMAIL: almira.rana31@gmail.com
      AUTH_PASS: ycna futf ghbn izus
      FRONTEND_URL: http://localhost:3033
      CORS_ORIGIN: http://localhost:3033
      GEMINI_API_KEY: AIzaSyD9YrZsRyLT7WUCjiwcP_wPT1YMKE-hSAc
    ports:
      - "3002:3002"

  frontend:
    image: alfarana/wads-pp-fp-frontend:latest
    restart: always
    environment:
      DB_NAME: BiancaTicketSystem
      DB_USER: PrettyPrincessAdmin
      DB_PASS: BiancaAdmin123!
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DIALECT: postgres
      DB_SSL: false
      PORT: 3033
      ACCESS_TOKEN_SECRET: buttwebbythesecond
      BASE_URL: http://localhost:3033
      AUTH_EMAIL: almira.rana31@gmail.com
      AUTH_PASS: ycna futf ghbn izus
      FRONTEND_URL: http://localhost:3033
      CORS_ORIGIN: http://localhost:3033
    depends_on:
      - backend
    ports:
      - "3001:3001"