name: Todolist CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wads-pp-fp-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/wads-pp-fp-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wads-pp-fp-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/wads-pp-fp-frontend:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Rootless Environment
        run: |
          echo "Setting up Docker rootless env..."
          echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          echo "export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock" >> $GITHUB_ENV

      - name: Pull Latest Backend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/wads-pp-fp-backend:latest

      - name: Pull Latest Frontend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/wads-pp-fp-frontend:latest

      - name: Stop and Remove Old Containers
        run: |
          docker compose down || true
          docker system prune -f

      - name: Run New Containers
        run: |
          docker compose up -d
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_SSL: ${{ secrets.DB_SSL }}
          PORT: ${{ secrets.PORT }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
          AUTH_PASS: ${{ secrets.AUTH_PASS }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}